---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sahil7879
spec:
  memberOf: [guests]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
